<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Exp{function extract(string $haystack,string $pattern){$placeholders=\Inilim\Tool\Method\Str\matchAll('/\{([^{}]+)}/',$pattern);$pattern=\preg_quote($pattern,'/');foreach($placeholders as $placeholder){$pattern=\Inilim\Tool\Method\Str\replace(\preg_quote('{'.$placeholder.'}','/'),'(?<'.$placeholder.'>[^\/]+?)',$pattern);}$pattern=\Inilim\Tool\Method\Str\replace(['\*','\{','\}'],['.*?','{','}'],$pattern);if(\preg_match("/^{$pattern}\$/i",$haystack,$matches)){return \array_intersect_key($matches,\array_flip($placeholders));}return[];}}namespace Inilim\Tool\Method\Arr{if(!\Inilim\Tool\Arr::__definedIfNot('from')){
    function from($items):array{$type=\gettype($items);if($type==='array'){return $items;}elseif($type==='object'){if(false){}elseif(\method_exists($items,'toArray')){return $items -> toArray();}elseif(\method_exists($items,'toJson')){return (array) \json_decode($items -> toJson(),true);}elseif(\Inilim\Tool\Method\Check\php80()&&$items instanceof \WeakMap){return \iterator_to_array($items,false);}elseif($items instanceof \Traversable){return \iterator_to_array($items);}elseif($items instanceof \JsonSerializable){return (array) $items -> jsonSerialize();}else{return (array) $items;}}throw new \InvalidArgumentException('Items cannot be represented by a scalar value.');}
    }}namespace Inilim\Tool\Method\Str{if(!\Inilim\Tool\Str::__definedIfNot('matchAll')){
    function matchAll(string $pattern,string $subject):array{\preg_match_all($pattern,$subject,$matches);if($matches[0]===[]){return[];}return $matches[1]?? $matches[0];}
    }if(!\Inilim\Tool\Str::__definedIfNot('replace')){
    function replace($search,$replace,$subject,bool $caseSensitive=true){if($search instanceof \Traversable){$search=\Inilim\Tool\Method\Arr\from($search);}if($replace instanceof \Traversable){$replace=\Inilim\Tool\Method\Arr\from($replace);}if($subject instanceof \Traversable){$subject=\Inilim\Tool\Method\Arr\from($subject);}return $caseSensitive?\str_replace($search,$replace,$subject):\str_ireplace($search,$replace,$subject);}
    }}namespace Inilim\Tool\Method\Check{if(!\Inilim\Tool\Check::__definedIfNot('php80')){
    function php80():bool{return \PHP_VERSION_ID>=80000?true:false;}
    }}