<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Exp{function findFromJsonViaSqlite(string $json,callable $callable,int $limit=10):?array{\Inilim\Tool\Method\Assert\extPhp('PDO');\Inilim\Tool\Method\Assert\extPhp('pdo_sqlite');\Inilim\Tool\Method\Assert\positiveInteger($limit);$results=\Inilim\Tool\Method\Other\tryCallWithErrHandler(static function()use($json,$callable,$limit){$pdo=new \PDO('sqlite::memory:',null,null,[]);$pdo -> exec('CREATE TABLE _table (_value TEXT)');$stmt=$pdo -> prepare('INSERT INTO _table (_value) VALUES (:_value)');$stmt -> execute(['_value'=>$json]);unset($json);$stmt=$pdo -> query('SELECT json_valid(_value) as valid FROM _table');$results=$stmt -> fetch(\PDO :: FETCH_NUM);if(!isset($results[0])||$results[0]==0){$pdo=$stmt=null;\Inilim\Tool\Method\Other\__setErrorLast(-1,'JSON invalid','',-1);return null;}$results=null;$pdo -> sqliteCreateFunction('FN_IS',static function($key,$value,$type,$fullkey)use($callable){switch($type){case 'real':$type='float';break;case 'text':$type='string';break;case 'integer':$type='int';break;case 'true':case 'false':$type='bool';break;}return (bool) $callable($key,$value,$type,\strtr($fullkey,['$.'=>'']));},4);$stmt=$pdo -> prepare('SELECT
                    tree.key, tree.value, tree.type, tree.fullkey
                FROM _table, json_tree(_table._value) as tree
                WHERE
                    tree.key not null
                    AND FN_IS(tree.key, tree.value, tree.type, tree.fullkey)
                LIMIT :limit');$stmt -> execute(['limit'=>$limit]);$results=$stmt -> fetchAll(\PDO :: FETCH_ASSOC);$pdo=$stmt=null;return $results;},static function($_,$msg){\Inilim\Tool\Method\Other\__setErrorLast(-1,$msg,'',-1);});if(!\is_array($results)){return null;}return $results;}}namespace Inilim\Tool\Method\Other{if(!\Inilim\Tool\Other::__definedIfNot('__setErrorLast')){
    function __setErrorLast(int $type,string $message,string $file,int $line):void{\Inilim\Tool\Method\Other\__state()-> error=['type'=>$type,'message'=>$message,'file'=>$file,'line'=>$line];}
    }if(!\Inilim\Tool\Other::__definedIfNot('__state')){
    function __state():object{static $o=null;return $o ??= new class{var?array $error=null;};}
    }if(!\Inilim\Tool\Other::__definedIfNot('extPhp')){
    function extPhp(string $ext,bool $rechecking=false):bool{static $o=null;$o ??=[];if(isset($o[$ext])&&!$rechecking){return $o[$ext];}return $o[$ext]=\extension_loaded($ext);}
    }if(!\Inilim\Tool\Other::__definedIfNot('getType')){
    function getType($v,bool $trueFalseAsSeparateType=false):string{$r=\gettype($v);switch($r){case 'NULL':return 'null';case 'double':return 'float';case 'object':if(\PHP_VERSION_ID>=80100&&$v instanceof \UnitEnum){return 'enum';}if($v instanceof \Throwable){return 'exception';}return 'object';case 'boolean':if($trueFalseAsSeparateType){return $v===true?'true':'false';}return 'bool';case 'integer':return 'int';case 'resource (closed)':return 'resource_closed';case 'unknown type':return 'unknown_type';default:return $r;}}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler')){
    function tryCallWithErrHandler(callable $callable,?callable $handler,int $errorLevels=\E_ALL){$use=['handler'=>$handler,'exception'=>null,'result'=>null,'obj'=>new \stdClass()];$wrapHandler=static function($levelOrCode,$message,$file,$line,$context=[])use(&$use){if($use['handler']===null){return true;}$context['isException']=isset($context['exception']);$context['isSuppress']=$context['isException']?false:!(\error_reporting()&$levelOrCode);$context['obj']=$use['obj'];try{$handlerResult=$use['handler']($levelOrCode,$message,$file,$line,$context);}catch(\Throwable $e){$use['exception']=$e;throw $e;}return $handlerResult!==false?true:false;};\set_error_handler($wrapHandler,$errorLevels);try{$use['result']=$callable($use['obj']);}catch(\Throwable $e){\restore_error_handler();if($use['exception']){throw $use['exception'];}$wrapHandler -> __invoke($e -> getCode(),$e -> getMessage(),$e -> getFile(),$e -> getLine(),['exception'=>$e]);return $use['result'];}\restore_error_handler();return $use['result'];}
    }if(!\Inilim\Tool\Other::__definedIfNot('valueToString')){
    function valueToString($value):string{$type=\Inilim\Tool\Method\Other\getType($value,true);if($type==='string'){return '"'.$value.'"';}if(\in_array($type,['true','false','null','resource','resource_closed','array'])){return $type;}if(\in_array($type,['object','exception'])){if(\method_exists($value,'__toString')){return \get_class($value).': '.\Inilim\Tool\Method\Other\valueToString($value -> __toString());}if($value instanceof \DateTime||$value instanceof \DateTimeImmutable){return \get_class($value).': '.\Inilim\Tool\Method\Other\valueToString($value -> format('c'));}return \get_class($value);}if($type==='enum'){if(\enum_exists(\get_class($value))){return \get_class($value).'::'.$value -> name;}return \get_class($value);}return (string) $value;}
    }}namespace Inilim\Tool\Method\Assert{if(!\Inilim\Tool\Assert::__definedIfNot('extPhp')){
    function extPhp(string $nameExt,string $message=''){if(!\Inilim\Tool\Method\Other\extPhp($nameExt)){throw new \InvalidArgumentException(\sprintf($message?:'PHP Extension "%s" not found',$nameExt));}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('positiveInteger')){
    function positiveInteger($value,string $message=''){if(!\Inilim\Tool\Method\Check\positiveInteger($value)){throw new \InvalidArgumentException(\sprintf($message?:'Expected a positive integer. Got: %s',\Inilim\Tool\Method\Other\valueToString($value)));}}
    }}namespace Inilim\Tool\Method\Check{if(!\Inilim\Tool\Check::__definedIfNot('positiveInteger')){
    function positiveInteger($value):bool{return \is_int($value)&&$value>0;}
    }}