<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Exp{function jsonWalkRecursiveViaSqlite(string $json,callable $callback,?int $limit=null,$valueBreak=false,array $types=[]):bool{if($limit!==null){\Inilim\Tool\Method\Assert\positiveInteger($limit);}if(!\Inilim\Tool\Method\Exp\jsonValidateViaSqlite($json)){\Inilim\Tool\Method\Other\__setErrorLast(-1,'JSON invalid','',-1);return false;}if($types){\Inilim\Tool\Method\Assert\allInArray($types,['bool','string','int','float','null','object','array']);foreach($types as&$type){switch($type){case 'float':$type='real';break;case 'string':$type='text';break;case 'int':$type='integer';break;case 'bool':$type='true';$types[]='false';break;}}$types=\array_map(static fn($t)=>'"'.$t.'"',$types);}$types=\implode(',',$types);$internal=static function()use($json,$callback,$limit,$valueBreak,$types){$pdo=new \PDO('sqlite::memory:',null,null,[\PDO :: ATTR_ERRMODE=>\PDO :: ERRMODE_EXCEPTION]);$pdo -> exec('CREATE TABLE _table (_name TEXT, _value TEXT)');$stmt=$pdo -> prepare('INSERT INTO _table (_name,_value) VALUES ("json",:_value)');$stmt -> execute(['_value'=>$json]);unset($json,$stmt);$pdo -> sqliteCreateFunction('FN_IT',static function($key,$value,$type,$fullkey)use(&$limit,$callback,$valueBreak){$fullkey=\strtr($fullkey,['$.'=>'']);switch($type){case 'real':$type='float';break;case 'text':$type='string';break;case 'integer':$type='int';break;case 'true':case 'false':$value=(bool) $value;$type='bool';break;}if($callback($key,$value,$type,$fullkey)===$valueBreak){throw new \Exception('ok');}if($limit!==null){$limit--;if($limit<=0){throw new \Exception('ok');}}return true;},4);$sql='SELECT 1 FROM _table, json_tree(_table._value) as tree
        WHERE tree.key not null '.($types?\sprintf('AND tree.type IN (%s)',$types):'').' AND FN_IT(tree.key, tree.value, tree.type, tree.fullkey) = 1';try{$pdo -> query($sql);}catch(\Exception $e){$m=$e -> getMessage();unset($e);if($m!=='ok'){\Inilim\Tool\Method\Other\__setErrorLast(-1,$m,'',-1);return false;}}return true;};$result=\Inilim\Tool\Method\Other\tryCallWithErrHandler($internal,static function($_,$msg){\Inilim\Tool\Method\Other\__setErrorLast(-1,$msg,'',-1);});if(!\is_bool($result)){return false;}return $result;}if(!\Inilim\Tool\Exp::__definedIfNot('jsonValidateViaSqlite')){
    function jsonValidateViaSqlite(string $json,int $flags=1):bool{\Inilim\Tool\Method\Assert\extPhp('PDO');\Inilim\Tool\Method\Assert\extPhp('pdo_sqlite');\Inilim\Tool\Method\Assert\inArray($flags,[1,2,3,4,5,6,7,8,9,10]);$curVer=\Inilim\Tool\Method\Other\sqliteLibVersion_m3();if(!\version_compare($curVer ?? '0.0.0','3.38.0','>=')){if($curVer===null){throw new \InvalidArgumentException('SQLite library version is not defined');}throw new \InvalidArgumentException(\sprintf('Your SQLite %s library version is lower than 3.38.0',$curVer));}$internal=static function()use($json,$flags,$curVer){$pdo=new \PDO('sqlite::memory:',null,null,[\PDO :: ATTR_ERRMODE=>\PDO :: ERRMODE_EXCEPTION]);if(\version_compare($curVer,'3.45.0','>=')){$stmt=$pdo -> prepare(\sprintf('SELECT json_valid(:json,%s) as valid',$flags));}else{$stmt=$pdo -> prepare('SELECT json_valid(:json) as valid');}$stmt -> execute(['json'=>$json]);unset($json);$result=$stmt -> fetch(\PDO :: FETCH_NUM);$pdo=$stmt=null;if(!isset($result[0])||$result[0]==0){return false;}return true;};$result=\Inilim\Tool\Method\Other\tryCallWithErrHandler_m2($internal);if(!\is_bool($result)){return false;}return $result;}
    }}namespace Inilim\Tool\Method\Other{if(!\Inilim\Tool\Other::__definedIfNot('__setErrorLast')){
    function __setErrorLast(int $type,string $message,string $file,int $line):void{\Inilim\Tool\Method\Other\__state()-> error=['type'=>$type,'message'=>$message,'file'=>$file,'line'=>$line];}
    }if(!\Inilim\Tool\Other::__definedIfNot('__state')){
    function __state():object{static $o=null;return $o ??= new class{var?array $error=null;};}
    }if(!\Inilim\Tool\Other::__definedIfNot('extPhp')){
    function extPhp(string $ext,bool $rechecking=false):bool{static $o=null;$o ??=[];if(isset($o[$ext])&&!$rechecking){return $o[$ext];}return $o[$ext]=\extension_loaded($ext);}
    }if(!\Inilim\Tool\Other::__definedIfNot('getType')){
    function getType($v,bool $trueFalseAsSeparateType=false):string{$r=\gettype($v);switch($r){case 'NULL':return 'null';case 'double':return 'float';case 'object':if(\PHP_VERSION_ID>=80100&&$v instanceof \UnitEnum){return 'enum';}if($v instanceof \Throwable){return 'exception';}return 'object';case 'boolean':if($trueFalseAsSeparateType){return $v===true?'true':'false';}return 'bool';case 'integer':return 'int';case 'resource (closed)':return 'resource_closed';case 'unknown type':return 'unknown_type';default:return $r;}}
    }if(!\Inilim\Tool\Other::__definedIfNot('sqliteLibVersion_m3')){
    function sqliteLibVersion_m3():?string{\Inilim\Tool\Method\Assert\extPhp('PDO');\Inilim\Tool\Method\Assert\extPhp('pdo_sqlite');$internal=static function(){$pdo=new \PDO('sqlite::memory:',null,null,[\PDO :: ATTR_ERRMODE=>\PDO :: ERRMODE_EXCEPTION]);$stmt=$pdo -> query('SELECT sqlite_version()',\PDO :: FETCH_NUM);$result=$stmt -> fetch();$pdo=$stmt=null;if(\is_array($result)){return $result[0]?? null;}return null;};$result=\Inilim\Tool\Method\Other\tryCallWithErrHandler_m2($internal);return \is_string($result)?$result:null;}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler')){
    function tryCallWithErrHandler(callable $callable,?callable $handler,int $errorLevels=\E_ALL){$use=['handler'=>$handler,'exception'=>null,'result'=>null,'obj'=>new \stdClass()];$wrapHandler=static function($levelOrCode,$message,$file,$line,$context=[])use(&$use){if($use['handler']===null){return true;}$context['isException']=isset($context['exception']);$context['isSuppress']=$context['isException']?false:!(\error_reporting()&$levelOrCode);$context['obj']=$use['obj'];try{$handlerResult=$use['handler']($levelOrCode,$message,$file,$line,$context);}catch(\Throwable $e){$use['exception']=$e;throw $e;}return $handlerResult!==false?true:false;};\set_error_handler($wrapHandler,$errorLevels);try{$use['result']=$callable($use['obj']);}catch(\Throwable $e){\restore_error_handler();if($use['exception']){throw $use['exception'];}$wrapHandler -> __invoke($e -> getCode(),$e -> getMessage(),$e -> getFile(),$e -> getLine(),['exception'=>$e]);return $use['result'];}\restore_error_handler();return $use['result'];}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler_m2')){
    function tryCallWithErrHandler_m2(callable $callable,?callable $handler=null,int $errorLevels=\E_ALL){if($handler===null){$handler=static function($levelOrCode,string $message,string $file,int $line){\Inilim\Tool\Method\Other\__setErrorLast((int) $levelOrCode,$message,$file,$line);};}return \Inilim\Tool\Method\Other\tryCallWithErrHandler($callable,$handler,$errorLevels);}
    }if(!\Inilim\Tool\Other::__definedIfNot('valueToString')){
    function valueToString($value):string{$type=\Inilim\Tool\Method\Other\getType($value,true);if($type==='string'){return '"'.$value.'"';}if(\in_array($type,['true','false','null','resource','resource_closed','array'])){return $type;}if(\in_array($type,['object','exception'])){if(\method_exists($value,'__toString')){return \get_class($value).': '.\Inilim\Tool\Method\Other\valueToString($value -> __toString());}if($value instanceof \DateTime||$value instanceof \DateTimeImmutable){return \get_class($value).': '.\Inilim\Tool\Method\Other\valueToString($value -> format('c'));}return \get_class($value);}if($type==='enum'){if(\enum_exists(\get_class($value))){return \get_class($value).'::'.$value -> name;}return \get_class($value);}return (string) $value;}
    }}namespace Inilim\Tool\Method\Assert{if(!\Inilim\Tool\Assert::__definedIfNot('allInArray')){
    function allInArray($value,$values,$message=''){\Inilim\Tool\Method\Assert\isIterable($value);foreach($value as $entry){\Inilim\Tool\Method\Assert\inArray($entry,$values,$message);}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('extPhp')){
    function extPhp(string $nameExt,string $message=''){if(!\Inilim\Tool\Method\Other\extPhp($nameExt)){throw new \InvalidArgumentException(\sprintf($message?:'PHP Extension "%s" not found',$nameExt));}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('inArray')){
    function inArray($value,array $values,string $message=''){if(!\in_array($value,$values,true)){throw new \InvalidArgumentException(\sprintf($message?:'Expected one of: %2$s. Got: %s',\Inilim\Tool\Method\Other\valueToString($value),\implode(', ',\array_map('\Inilim\Tool\Method\Other\valueToString',$values))));}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('isIterable')){
    function isIterable($value,string $message=''){if(!\Inilim\Tool\Method\Check\isIterable($value)){throw new \InvalidArgumentException(\sprintf($message?:'Expected an iterable. Got: %s',\Inilim\Tool\Method\Other\getType($value)));}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('positiveInteger')){
    function positiveInteger($value,string $message=''){if(!\Inilim\Tool\Method\Check\positiveInteger($value)){throw new \InvalidArgumentException(\sprintf($message?:'Expected a positive integer. Got: %s',\Inilim\Tool\Method\Other\valueToString($value)));}}
    }}namespace Inilim\Tool\Method\Check{if(!\Inilim\Tool\Check::__definedIfNot('isIterable')){
    function isIterable($value):bool{return \is_array($value)||$value instanceof \Traversable;}
    }if(!\Inilim\Tool\Check::__definedIfNot('positiveInteger')){
    function positiveInteger($value):bool{return \is_int($value)&&$value>0;}
    }}