<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Other{function agentDetector():array{$aiAgent=\getenv('AI_AGENT');if(\is_string($aiAgent)&&($aiAgent=\Inilim\Tool\Method\LarStr\trim($aiAgent))!==''){$normalized=\preg_replace('/(\-|\_)(cli|ai|agent)$/','',\Inilim\Tool\Method\Str\lower($aiAgent));return['status'=>true,'name'=>$normalized];}foreach(\Inilim\Tool\Method\Data\agentsEnvVars()as $agent=>$envVars){foreach($envVars as $envVar){if(\getenv($envVar)!==false){return['status'=>true,'name'=>$agent];}}}if(\Inilim\Tool\Method\FS\isFile('/opt/.devin')){return['status'=>true,'name'=>'devin'];}return['status'=>false,'name'=>null];}if(!\Inilim\Tool\Other::__definedIfNot('__setErrorLast')){
    function __setErrorLast(int $type,string $message,string $file,int $line):void{\Inilim\Tool\Method\Other\__state()-> error=['type'=>$type,'message'=>$message,'file'=>$file,'line'=>$line];}
    }if(!\Inilim\Tool\Other::__definedIfNot('__state')){
    function __state():object{static $o=null;return $o ??= new class{var?array $error=null;};}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler')){
    function tryCallWithErrHandler(callable $callable,?callable $handler,int $errorLevels=\E_ALL){$use=['handler'=>$handler,'exception'=>null,'result'=>null,'obj'=>new \stdClass()];$wrapHandler=static function($levelOrCode,$message,$file,$line,$context=[])use(&$use){if($use['handler']===null){return true;}$context['isException']=isset($context['exception']);$context['isSuppress']=$context['isException']?false:!(\error_reporting()&$levelOrCode);$context['obj']=$use['obj'];try{$handlerResult=$use['handler']($levelOrCode,$message,$file,$line,$context);}catch(\Throwable $e){$use['exception']=$e;throw $e;}return $handlerResult!==false?true:false;};\set_error_handler($wrapHandler,$errorLevels);try{$use['result']=$callable($use['obj']);}catch(\Throwable $e){\restore_error_handler();if($use['exception']){throw $use['exception'];}$wrapHandler -> __invoke($e -> getCode(),$e -> getMessage(),$e -> getFile(),$e -> getLine(),['exception'=>$e]);return $use['result'];}\restore_error_handler();return $use['result'];}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler_m2')){
    function tryCallWithErrHandler_m2(callable $callable,?callable $handler=null,int $errorLevels=\E_ALL){if($handler===null){$handler=static function($levelOrCode,string $message,string $file,int $line){\Inilim\Tool\Method\Other\__setErrorLast((int) $levelOrCode,$message,$file,$line);};}return \Inilim\Tool\Method\Other\tryCallWithErrHandler($callable,$handler,$errorLevels);}
    }}namespace Inilim\Tool\Method\Data{if(!\Inilim\Tool\Data::__definedIfNot('agentsEnvVars')){
    function agentsEnvVars():\Generator{yield 'cline'=>['CLINE_ACTIVE'];yield 'trae'=>['TRAE_AI_SHELL_ID'];yield 'cursor'=>['CURSOR_AGENT','CURSOR_TRACE_ID'];yield 'gemini'=>['GEMINI_CLI'];yield 'codex'=>['CODEX_SANDBOX','CODEX_THREAD_ID','CODEX_CI'];yield 'augment'=>['AUGMENT_AGENT'];yield 'opencode'=>['OPENCODE_CLIENT','OPENCODE','OPENCODE_CALLER'];yield 'amp'=>['AMP_CURRENT_THREAD_ID'];yield 'cowork'=>['CLAUDE_CODE_IS_COWORK'];yield 'claude'=>['CLAUDECODE','CLAUDE_CODE'];yield 'replit'=>['REPL_ID'];yield 'copilot'=>['COPILOT_CLI','COPILOT_MODEL','COPILOT_ALLOW_ALL','COPILOT_GITHUB_TOKEN'];yield 'antigravity'=>['ANTIGRAVITY_AGENT'];yield 'goose'=>['GOOSE_PROVIDER'];yield 'pi'=>['PI_CODING_AGENT'];yield 'kiro'=>['KIRO_AGENT_PATH'];}
    }}namespace Inilim\Tool\Method\Str{if(!\Inilim\Tool\Str::__definedIfNot('__state')){
    function __state(){static $o=null;return $o ??= new class{const INVISIBLE_CHARACTERS='\x{0009}\x{0020}\x{00A0}\x{00AD}\x{034F}\x{061C}\x{115F}\x{1160}\x{17B4}\x{17B5}\x{180E}\x{2000}\x{2001}\x{2002}\x{2003}\x{2004}\x{2005}\x{2006}\x{2007}\x{2008}\x{2009}\x{200A}\x{200B}\x{200C}\x{200D}\x{200E}\x{200F}\x{202F}\x{205F}\x{2060}\x{2061}\x{2062}\x{2063}\x{2064}\x{2065}\x{206A}\x{206B}\x{206C}\x{206D}\x{206E}\x{206F}\x{3000}\x{2800}\x{3164}\x{FEFF}\x{FFA0}\x{1D159}\x{1D173}\x{1D174}\x{1D175}\x{1D176}\x{1D177}\x{1D178}\x{1D179}\x{1D17A}\x{E0020}';var $randomStringFactory;};}
    }if(!\Inilim\Tool\Str::__definedIfNot('lower')){
    function lower(string $value,?string $encoding='UTF-8'):string{return \mb_strtolower($value,$encoding);}
    }}namespace Inilim\Tool\Method\FS{if(!\Inilim\Tool\FS::__definedIfNot('isFile')){
    function isFile(string $filename):bool{$value=\Inilim\Tool\Method\Other\tryCallWithErrHandler_m2(static function()use($filename){\clearstatcache(false,$filename);return \is_file($filename);});return $value===null?false:$value;}
    }}namespace Inilim\Tool\Method\LarStr{if(!\Inilim\Tool\LarStr::__definedIfNot('trim')){
    function trim($value,$charlist=null){if($charlist===null){$trimDefaultCharacters=\preg_quote(" \n\r\t\v\x00");$c=\Inilim\Tool\Method\Str\__state():: INVISIBLE_CHARACTERS;return \preg_replace('~^[\s'.$c.$trimDefaultCharacters.']+|[\s'.$c.$trimDefaultCharacters.']+$~u','',$value)?? \trim($value);}return \trim($value,$charlist);}
    }}