<?php

namespace Inilim\Tool\Method\Other{function prepareArrayForSerializeRecursive(array&$value){\array_walk_recursive($value,static function(&$subVal){if(\is_object($subVal)){$subVal=\Inilim\Tool\Method\Other\prepareObjForSerialize($subVal);}elseif(\is_resource($subVal)){$subVal=\print_r($subVal,true);}});}if(!\Inilim\Tool\Other::__definedIfNot('getExceptionDetails')){
    function getExceptionDetails(\Throwable $e,bool $traceAsArray=false){return['message'=>$e -> getMessage(),'line'=>$e -> getLine(),'code'=>$e -> getCode(),'file'=>$e -> getFile(),'trace'=>$traceAsArray?$e -> getTrace():$e -> getTraceAsString(),'class'=>\get_class($e)];}
    }if(!\Inilim\Tool\Other::__definedIfNot('prepareObjForSerialize')){
    function prepareObjForSerialize(object $obj){$e=null;if($obj instanceof \JsonSerializable){$v=\Inilim\Tool\Method\Other\tryCallMethod($obj,'jsonSerialize',[],null,$e);/*// jsonSerialize return mixed OR throw exception*/if($e===null){$v=[$v];\Inilim\Tool\Method\Other\prepareArrayForSerializeRecursive($v);return $v[0];}}$e=null;if($obj instanceof \Serializable){/*// __serialize return mixed OR throw exception*/$v=\Inilim\Tool\Method\Other\tryCallMethod($obj,'__serialize',[],null,$e);if($e===null){$v=[$v];\Inilim\Tool\Method\Other\prepareArrayForSerializeRecursive($v);return $v[0];}}$e=null;if(\PHP_VERSION_ID>=80100&&$obj instanceof \UnitEnum){return \get_class($obj).'::'.$obj -> name;}if(\method_exists($obj,'toArray')){$v=\Inilim\Tool\Method\Other\tryCallMethod($obj,'toArray',[],null,$e);if($e===null&&\is_array($v)){\Inilim\Tool\Method\Other\prepareArrayForSerializeRecursive($v);return $v;}}$e=null;if($obj instanceof \Throwable){$v=\Inilim\Tool\Method\Other\getExceptionDetails($obj,true);\Inilim\Tool\Method\Other\prepareArrayForSerializeRecursive($v);return $v;}$v=(array) $obj;\Inilim\Tool\Method\Other\prepareArrayForSerializeRecursive($v);return $v;}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallCallable')){
    function tryCallCallable($callable,array $args=[],$default=null,?\Throwable&$exception=null){try{if(!\is_callable($callable)){throw new \Exception('$callable give not callable');}$result=\call_user_func($callable,... $args);}catch(\Throwable $e){$exception=$e;return $default;}return $result;}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallMethod')){
    function tryCallMethod($objectOrClass,string $methodName,array $args=[],$default=null,?\Throwable&$exception=null){return \Inilim\Tool\Method\Other\tryCallCallable([$objectOrClass,$methodName],$args,$default,$exception);}
    }}