<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Zip{function extractByCallable($pathToFileOrZip,callable $predicate,?string $dir=null):?array{$zip=\Inilim\Tool\Method\Zip\getObjFrom($pathToFileOrZip);if($zip===null){return null;}$procedure=static function()use($zip,$predicate,$dir){if($dir===null){$_dir=\sys_get_temp_dir();}else{$_dir=\realpath($dir);if($_dir===false){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('Dir "%s" not exist',$dir),'',-1);return null;}}$gen=\Inilim\Tool\Method\Zip\scanAsGenerator($zip);if($gen===null){return null;}$results=[];foreach($gen as $stat){$t=$stat;if($predicate($t)!==true){continue;}$t=null;$resource=\Inilim\Tool\Method\Zip\getResourceByIdx($zip,$stat['index']);if(!$resource){$stat['status']=false;$results[]=$stat;continue;}$pathToFile=$_dir.'/inilim-tools-zip-'.\Inilim\Tool\Method\ID\uuidv7().'.tmp';if(!\Inilim\Tool\Method\Other\resourceContentWriteToFile($resource,$pathToFile)){$stat['status']=false;$results[]=$stat;continue;}$stat['status']=true;$stat['path_to_file']=$pathToFile;$results[]=$stat;}return $results;};return \Inilim\Tool\Method\Other\tryCallWithErrHandler($procedure,static function(){\Inilim\Tool\Method\Other\__setErrorLast(-1,(string) \func_get_arg(1),'',-1);});}if(!\Inilim\Tool\Zip::__definedIfNot('getObjFrom')){
    function getObjFrom($pathToFileOrZip):?object{\Inilim\Tool\Method\Assert\extPhp('zip');$type=\Inilim\Tool\Method\Other\getType($pathToFileOrZip);if($type==='string'){if(!\Inilim\Tool\Method\FS\isFile($pathToFileOrZip)){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('File "%s", not exist',$pathToFileOrZip),'',-1);return null;}$zip=\Inilim\Tool\Method\Zip\open($pathToFileOrZip);if(!$zip){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('File "%s", open failed',$pathToFileOrZip),'',-1);return null;}}elseif($type==='object'){if(!$pathToFileOrZip instanceof \ZipArchive){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('Expected (arg #0) a string or \ZipArchive. Got: %s',\get_class($pathToFileOrZip)),'',-1);return null;}$zip=$pathToFileOrZip;if($zip -> filename===''){\Inilim\Tool\Method\Other\__setErrorLast(-1,'Uninitialized zip','',-1);return null;}}else{\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('Expected (arg #0) a string or \ZipArchive. Got: %s',$type),'',-1);return null;}return $zip;}
    }if(!\Inilim\Tool\Zip::__definedIfNot('getResourceByIdx')){
    function getResourceByIdx(\ZipArchive $zip,int $idx){return \Inilim\Tool\Method\Other\tryCallWithErrHandler(static function()use($zip,$idx){if(\Inilim\Tool\Method\Check\php80()){$resource=$zip -> getStreamIndex($idx,\ZipArchive :: FL_UNCHANGED);}else{$stat=$zip -> statIndex($idx);if($stat===false){return null;}$resource=$zip -> getStream($stat['name']);}return $resource===false?null:$resource;},static function(){\Inilim\Tool\Method\Other\__setErrorLast(-1,(string) \func_get_arg(1),'',-1);});}
    }if(!\Inilim\Tool\Zip::__definedIfNot('open')){
    function open(string $filename,int $flags=0):?\ZipArchive{\Inilim\Tool\Method\Assert\extPhp('zip');$_filename=\Inilim\Tool\Method\Path\realPath($filename);if(!$_filename){\Inilim\Tool\Method\Other\__setErrorLast(-1,'File not found',$filename,-1);return null;}$_filename=\Inilim\Tool\Method\Path\normalize($_filename);$zip=new \ZipArchive();$status=\Inilim\Tool\Method\Other\tryCallWithErrHandler(static fn()=>$zip -> open($_filename,$flags),null);if($status!==true){if(\is_int($status)){$errors=[\ZipArchive :: ER_EXISTS=>'File already exists',\ZipArchive :: ER_INCONS=>'Zip archive inconsistent',\ZipArchive :: ER_INVAL=>'Invalid argument',\ZipArchive :: ER_MEMORY=>'Memory allocation failure',\ZipArchive :: ER_NOENT=>'No such file',\ZipArchive :: ER_NOZIP=>'Not a zip archive',\ZipArchive :: ER_OPEN=>'Can\'t open file',\ZipArchive :: ER_READ=>'Read error',\ZipArchive :: ER_SEEK=>'Seek error'];\Inilim\Tool\Method\Other\__setErrorLast(-1,$errors[$status]?? 'Zip open failed',$filename,-1);}else{\Inilim\Tool\Method\Other\__setErrorLast(-1,'Zip open failed',$filename,-1);}return null;}return $zip;}
    }if(!\Inilim\Tool\Zip::__definedIfNot('scanAsGenerator')){
    function scanAsGenerator($pathToFileOrZip):?\Generator{$zip=\Inilim\Tool\Method\Zip\getObjFrom($pathToFileOrZip);if($zip===null){return null;}$num=$zip -> numFiles;for($i=0;$i<$num;$i++){$ri=$zip -> statIndex($i,\ZipArchive :: FL_UNCHANGED);if($ri===false){continue;}yield $ri;}}
    }}namespace Inilim\Tool\Method\Path{if(!\Inilim\Tool\Path::__definedIfNot('normalize')){
    function normalize(string $path):string{$path=\strtr($path,'\\','/');$path=\Inilim\Tool\Method\Str\deduplicate($path,'/');if(':'===\Inilim\Tool\Method\Str\substr($path,1,1)){$path=\Inilim\Tool\Method\Str\ucfirst($path);}return $path;}
    }if(!\Inilim\Tool\Path::__definedIfNot('realPath')){
    function realPath(string $path):?string{$value=\Inilim\Tool\Method\Other\tryCallWithErrHandler(static fn()=>\realpath($path),null);return $value===false?null:$value;}
    }}namespace Inilim\Tool\Method\Str{if(!\Inilim\Tool\Str::__definedIfNot('deduplicate')){
    function deduplicate(string $string,string $character=' '){return \preg_replace('/'.\preg_quote($character,'/').'+/u',$character,$string);}
    }if(!\Inilim\Tool\Str::__definedIfNot('substr')){
    function substr(string $string,int $start,?int $length=null,string $encoding='UTF-8'){return \mb_substr($string,$start,$length,$encoding);}
    }if(!\Inilim\Tool\Str::__definedIfNot('ucfirst')){
    function ucfirst(string $string):string{return \Inilim\Tool\Method\Str\upper(\Inilim\Tool\Method\Str\substr($string,0,1)).\Inilim\Tool\Method\Str\substr($string,1);}
    }if(!\Inilim\Tool\Str::__definedIfNot('upper')){
    function upper(string $value,?string $encoding='UTF-8'):string{return \mb_strtoupper($value,$encoding);}
    }}namespace Inilim\Tool\Method\Other{if(!\Inilim\Tool\Other::__definedIfNot('__setErrorLast')){
    function __setErrorLast(int $type,string $message,string $file,int $line):void{\Inilim\Tool\Method\Other\__state()-> error=['type'=>$type,'message'=>$message,'file'=>$file,'line'=>$line];}
    }if(!\Inilim\Tool\Other::__definedIfNot('__state')){
    function __state():object{static $o=null;return $o ??= new class{var?array $error=null;};}
    }if(!\Inilim\Tool\Other::__definedIfNot('extPhp')){
    function extPhp(string $ext,bool $rechecking=false):bool{static $o=null;$o ??=[];if(isset($o[$ext])&&!$rechecking){return $o[$ext];}return $o[$ext]=\extension_loaded($ext);}
    }if(!\Inilim\Tool\Other::__definedIfNot('getType')){
    function getType($v,bool $trueFalseAsSeparateType=false):string{$r=\gettype($v);switch($r){case 'NULL':return 'null';case 'double':return 'float';case 'object':if(\PHP_VERSION_ID>=80100&&$v instanceof \UnitEnum){return 'enum';}if($v instanceof \Throwable){return 'exception';}return 'object';case 'boolean':if($trueFalseAsSeparateType){return $v===true?'true':'false';}return 'bool';case 'integer':return 'int';case 'resource (closed)':return 'resource_closed';case 'unknown type':return 'unknown_type';default:return $r;}}
    }if(!\Inilim\Tool\Other::__definedIfNot('resourceContentWriteToFile')){
    function resourceContentWriteToFile($resource,string $pathToFile):?string{\Inilim\Tool\Method\Assert\resource($resource);return \Inilim\Tool\Method\Other\tryCallWithErrHandler(static function()use(&$resource,$pathToFile){$targetResource=\fopen($pathToFile,'wb');if($targetResource===false){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('fopen("%s") failed',$pathToFile),'',-1);return null;}$curPos=\ftell($resource);\rewind($resource);while(true){$data=\fread($resource,8192);if($data===false){\Inilim\Tool\Method\Other\__setErrorLast(-1,'fread(arg#0) failed','',-1);break;}if(\fwrite($targetResource,$data)===false){\Inilim\Tool\Method\Other\__setErrorLast(-1,\sprintf('fwrite("%s") failed',$pathToFile),'',-1);break;}if(\feof($resource)){break;}}\fclose($targetResource);\fseek($resource,$curPos);return $pathToFile;},null);}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler')){
    function tryCallWithErrHandler(callable $callable,?callable $handler,int $errorLevels=\E_ALL){$use=['handler'=>$handler,'exception'=>null,'result'=>null,'obj'=>new \stdClass()];$wrapHandler=static function($levelOrCode,$message,$file,$line,$context=[])use(&$use){if($use['handler']===null){return true;}$context['isException']=isset($context['exception']);$context['isSuppress']=$context['isException']?false:!(\error_reporting()&$levelOrCode);$context['obj']=$use['obj'];try{$handlerResult=$use['handler']($levelOrCode,$message,$file,$line,$context);}catch(\Throwable $e){$use['exception']=$e;throw $e;}return $handlerResult!==false?true:false;};\set_error_handler($wrapHandler,$errorLevels);try{$use['result']=$callable($use['obj']);}catch(\Throwable $e){\restore_error_handler();if($use['exception']){throw $use['exception'];}$wrapHandler -> __invoke($e -> getCode(),$e -> getMessage(),$e -> getFile(),$e -> getLine(),['exception'=>$e]);return $use['result'];}\restore_error_handler();return $use['result'];}
    }if(!\Inilim\Tool\Other::__definedIfNot('tryCallWithErrHandler_m2')){
    function tryCallWithErrHandler_m2(callable $callable,?callable $handler=null,int $errorLevels=\E_ALL){if($handler===null){$handler=static function($levelOrCode,$message,$file,$line){\Inilim\Tool\Method\Other\__setErrorLast($levelOrCode,$message,$file,$line);};}return \Inilim\Tool\Method\Other\tryCallWithErrHandler($callable,$handler,$errorLevels);}
    }}namespace Inilim\Tool\Method\FS{if(!\Inilim\Tool\FS::__definedIfNot('isFile')){
    function isFile(string $filename):bool{$value=\Inilim\Tool\Method\Other\tryCallWithErrHandler_m2(static function()use($filename){\clearstatcache(false,$filename);return \is_file($filename);});return $value===null?false:$value;}
    }}namespace Inilim\Tool\Method\ID{if(!\Inilim\Tool\ID::__definedIfNot('uuidFromHex')){
    function uuidFromHex(string $uhex,int $version):string{return \sprintf('%08s-%04s-%04x-%04x-%12s',\substr($uhex,0,8),\substr($uhex,8,4),\hexdec(\substr($uhex,12,4))&0xfff|$version << 12,\hexdec(\substr($uhex,16,4))&0x3fff|0x8000,\substr($uhex,20,12));}
    }if(!\Inilim\Tool\ID::__definedIfNot('uuidv7')){
    function uuidv7():string{$uhex=\substr(\str_pad(\dechex(\Inilim\Tool\Method\Time\unixMs()),12,'0',\STR_PAD_LEFT),-12);$uhex .= \bin2hex(\random_bytes(10));return \Inilim\Tool\Method\ID\uuidFromHex($uhex,7);}
    }}namespace Inilim\Tool\Method\Time{if(!\Inilim\Tool\Time::__definedIfNot('unixMs')){
    function unixMs():int{$t=\microtime(false);return \intval(\substr($t,11).\substr($t,2,3));}
    }}namespace Inilim\Tool\Method\Assert{if(!\Inilim\Tool\Assert::__definedIfNot('extPhp')){
    function extPhp(string $nameExt,string $message=''){if(!\Inilim\Tool\Method\Other\extPhp($nameExt)){throw new \InvalidArgumentException(\sprintf($message?:'PHP Extension "%s" not found',$nameExt));}}
    }if(!\Inilim\Tool\Assert::__definedIfNot('resource')){
    function resource($value,?string $type=null,string $message=''){if($type!==null&&!\Inilim\Tool\Method\Check\resource($value,$type)){throw new \InvalidArgumentException(\sprintf($message?:'Expected a resource of type %2$s. Got: %s',\Inilim\Tool\Method\Other\getType($value),$type));}if(!\Inilim\Tool\Method\Check\resource($value)){throw new \InvalidArgumentException(\sprintf($message?:'Expected a resource. Got: %s',\Inilim\Tool\Method\Other\getType($value),$type));}}
    }}namespace Inilim\Tool\Method\Check{if(!\Inilim\Tool\Check::__definedIfNot('php80')){
    function php80():bool{return \PHP_VERSION_ID>=80000?true:false;}
    }if(!\Inilim\Tool\Check::__definedIfNot('resource')){
    function resource($value,?string $type=null):bool{if(!\is_resource($value)){return false;}if($type&&$type!==\get_resource_type($value)){return false;}return true;}
    }}