<?php

declare(strict_types=1);namespace Inilim\Tool\Method\Integer{function strDecrement(string $value):string{if(!\Inilim\Tool\Method\Integer\isNumeric($value)){return \Inilim\Tool\Method\PF\str_decrement($value);}if($value==='0'){return '-'.\Inilim\Tool\Method\PF\str_increment($value);}elseif(\Inilim\Tool\Method\PF\str_starts_with($value,'-')){$value=\ltrim($value,'-');return '-'.\Inilim\Tool\Method\PF\str_increment($value);}return \Inilim\Tool\Method\PF\str_decrement($value);}if(!\Inilim\Tool\Integer::__definedIfNot('isNumeric')){
    function isNumeric($v):bool{$t=\gettype($v);if(!\in_array($t,['string','integer'],true)){return false;}if($t==='integer'||\preg_match('#^\-?[1-9][0-9]{0,}$|^0$#',$v)){return true;}return false;}
    }}namespace Inilim\Tool\Method\Check{if(!\Inilim\Tool\Check::__definedIfNot('php80')){
    function php80():bool{return \PHP_VERSION_ID>=80000?true:false;}
    }if(!\Inilim\Tool\Check::__definedIfNot('php83')){
    function php83():bool{return \PHP_VERSION_ID>=80300?true:false;}
    }}namespace Inilim\Tool\Method\PF{if(!\Inilim\Tool\PF::__definedIfNot('str_contains')){
    function str_contains(string $haystack,string $needle):bool{if(\Inilim\Tool\Method\Check\php80()){return \str_contains($haystack,$needle);}return ''===$needle||false!==\strpos($haystack,$needle);}
    }if(!\Inilim\Tool\PF::__definedIfNot('str_decrement')){
    function str_decrement(string $string):string{if(\Inilim\Tool\Method\Check\php83()){try{return \str_decrement($string);}catch(\ValueError $e){$message=$e -> getMessage();if(\Inilim\Tool\Method\PF\str_contains($message,'ASCII')){throw new \Error('PF::str_decrement(): Argument #1 ($string) must be composed only of alphanumeric ASCII characters');}elseif(\Inilim\Tool\Method\PF\str_contains($message,'range')){throw new \Error(\sprintf('PF::str_decrement(): Argument #1 ($string) "%s" is out of decrement range',$string));}throw new \Error('PF::str_decrement(): Argument #1 ($string) cannot be empty');}}if(''===$string){throw new \Error('PF::str_decrement(): Argument #1 ($string) cannot be empty');}if(!\preg_match('/^[a-zA-Z0-9]+$/',$string)){throw new \Error('PF::str_decrement(): Argument #1 ($string) must be composed only of alphanumeric ASCII characters');}if(\preg_match('/\A(?:0[aA0]?|[aA])\z/',$string)){throw new \Error(\sprintf('PF::str_decrement(): Argument #1 ($string) "%s" is out of decrement range',$string));}if(!\in_array(\substr($string,-1),['A','a','0'],true)){return \implode('',\array_slice(\str_split($string),0,-1)).\chr(\ord(\substr($string,-1))-1);}$carry='';$decremented='';for($i=\strlen($string)-1;$i>=0;--$i){$char=$string[$i];switch($char){case 'A':if(''!==$carry){$decremented=$carry.$decremented;$carry='';}$carry='Z';break;case 'a':if(''!==$carry){$decremented=$carry.$decremented;$carry='';}$carry='z';break;case '0':if(''!==$carry){$decremented=$carry.$decremented;$carry='';}$carry='9';break;case '1':if(''!==$carry){$decremented=$carry.$decremented;$carry='';}break;default:if(''!==$carry){$decremented=$carry.$decremented;$carry='';}if(!\in_array($char,['A','a','0'],true)){$decremented=\chr(\ord($char)-1).$decremented;}}}return $decremented;}
    }if(!\Inilim\Tool\PF::__definedIfNot('str_increment')){
    function str_increment(string $string):string{if(\Inilim\Tool\Method\Check\php83()){try{return \str_increment($string);}catch(\ValueError $e){$message=$e -> getMessage();if(\Inilim\Tool\Method\PF\str_contains($message,'ASCII')){throw new \Error('PF::str_increment(): Argument #1 ($string) must be composed only of alphanumeric ASCII characters');}throw new \Error('PF::str_increment(): Argument #1 ($string) cannot be empty');}}if(''===$string){throw new \Error('PF::str_increment(): Argument #1 ($string) cannot be empty');}if(!\preg_match('/^[a-zA-Z0-9]+$/',$string)){throw new \Error('PF::str_increment(): Argument #1 ($string) must be composed only of alphanumeric ASCII characters');}if(\is_numeric($string)){$offset=\stripos($string,'e');if(false!==$offset){$char=$string[$offset];++$char;$string[$offset]=$char;++$string;switch($string[$offset]){case 'f':$string[$offset]='e';break;case 'F':$string[$offset]='E';break;case 'g':$string[$offset]='f';break;case 'G':$string[$offset]='F';break;}return (string) $string;}}return (string)++$string;}
    }if(!\Inilim\Tool\PF::__definedIfNot('str_starts_with')){
    function str_starts_with(string $haystack,string $needle):bool{if(\Inilim\Tool\Method\Check\php80()){return \str_starts_with($haystack,$needle);}return 0===\strncmp($haystack,$needle,\strlen($needle));}
    }}