<?php

namespace Inilim\Tool\Method\Arr{function sortBy(array $arr,string $by,int $options=\SORT_REGULAR,bool $descending=false):array{$t=[];foreach($arr as $key=>$value){if(\is_array($value)||\is_object($value)){$t[$key]=\Inilim\Tool\Method\Arr\dataGet($value,$by);}else{$t[$key]=null;}}$descending?\arsort($t,$options):\asort($t,$options);foreach(\array_keys($t)as $key){$t[$key]=$arr[$key];}return $t;}if(!\Inilim\Tool\Arr::__definedIfNot('accessible')){
    function accessible($value){return \is_array($value)||$value instanceof \ArrayAccess;}
    }if(!\Inilim\Tool\Arr::__definedIfNot('collapse')){
    function collapse(iterable $array){$results=[];foreach($array as $values){if(!\is_array($values)){continue;}$results[]=$values;}return \array_merge([],... $results);}
    }if(!\Inilim\Tool\Arr::__definedIfNot('dataGet')){
    function dataGet($target,$key,$default=null){if($key===null){return $target;}$key=\is_array($key)?$key:\explode('.',$key);foreach($key as $i=>$segment){unset($key[$i]);if($segment===null){return $target;}if($segment==='*'){if(!\is_iterable($target)){return \Inilim\Tool\Method\Arr\value($default);}$result=[];foreach($target as $item){$result[]=\Inilim\Tool\Method\Arr\dataGet($item,$key);}return \in_array('*',$key)?\Inilim\Tool\Method\Arr\collapse($result):$result;}switch($segment){case '\*':$segment='*';break;case '\{first}':$segment='{first}';break;case '{first}':$segment=\array_key_first(\is_array($target)?$target:\Inilim\Tool\Method\Arr\getArrayableItems($target));break;case '\{last}':$segment='{last}';break;case '{last}':$segment=\array_key_last(\is_array($target)?$target:\Inilim\Tool\Method\Arr\getArrayableItems($target));break;}if(\Inilim\Tool\Method\Arr\accessible($target)&&\Inilim\Tool\Method\Arr\exists($target,$segment)){$target=$target[$segment];}elseif(\is_object($target)&&isset($target ->{$segment})){$target=$target ->{$segment};}else{return $default;}}return $target;}
    }if(!\Inilim\Tool\Arr::__definedIfNot('exists')){
    function exists($array,$key){if($array instanceof \ArrayAccess){return $array -> offsetExists($key);}return \array_key_exists($key,$array);}
    }if(!\Inilim\Tool\Arr::__definedIfNot('getArrayableItems')){
    function getArrayableItems($items){if(\is_array($items)){return $items;}switch(true){case \PHP_VERSION_ID>=80000&&$items instanceof \WeakMap:throw new \InvalidArgumentException('Collections can not be created using instances of WeakMap.');case $items instanceof \Traversable:return \iterator_to_array($items);case $items instanceof \JsonSerializable:return (array) $items -> jsonSerialize();case \PHP_VERSION_ID>=80100&&$items instanceof \UnitEnum:return[$items];}return (array) $items;}
    }if(!\Inilim\Tool\Arr::__definedIfNot('value')){
    function value($value){return $value instanceof \Closure?$value():$value;}
    }}