<?php

$root = \dirname(__DIR__);

return [
    [
        'method' => 'Inilim\Tool\Method\File',
        'tool'   => $class = \Inilim\Tool\File::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/File',
        'pathMin'   => $root . '/src/MethodMin/File',
        'pathToClass' => $root . '/src/File.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Path',
        'tool'   => $class = \Inilim\Tool\Path::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Path',
        'pathMin'   => $root . '/src/MethodMin/Path',
        'pathToClass' => $root . '/src/Path.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Arr',
        'tool'   => $class = \Inilim\Tool\Arr::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Arr',
        'pathMin'   => $root . '/src/MethodMin/Arr',
        'pathToClass' => $root . '/src/Arr.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Integer',
        'tool'   => $class = \Inilim\Tool\Integer::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Integer',
        'pathMin'   => $root . '/src/MethodMin/Integer',
        'pathToClass' => $root . '/src/Integer.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Double',
        'tool'   => $class = \Inilim\Tool\Double::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Double',
        'pathMin'   => $root . '/src/MethodMin/Double',
        'pathToClass' => $root . '/src/Double.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Data',
        'tool'   => $class = \Inilim\Tool\Data::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Data',
        'pathMin'   => $root . '/src/MethodMin/Data',
        'pathToClass' => $root . '/src/Data.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Str',
        'tool'   => $class = \Inilim\Tool\Str::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Str',
        'pathMin'   => $root . '/src/MethodMin/Str',
        'pathToClass' => $root . '/src/Str.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Other',
        'tool'   => $class = \Inilim\Tool\Other::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Other',
        'pathMin'   => $root . '/src/MethodMin/Other',
        'pathToClass' => $root . '/src/Other.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Json',
        'tool'   => $class = \Inilim\Tool\Json::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Json',
        'pathMin'   => $root . '/src/MethodMin/Json',
        'pathToClass' => $root . '/src/Json.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\FS',
        'tool'   => $class = \Inilim\Tool\FS::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/FS',
        'pathMin'   => $root . '/src/MethodMin/FS',
        'pathToClass' => $root . '/src/FS.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Zip',
        'tool'   => $class = \Inilim\Tool\Zip::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Zip',
        'pathMin'   => $root . '/src/MethodMin/Zip',
        'pathToClass' => $root . '/src/Zip.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Refl',
        'tool'   => $class = \Inilim\Tool\Refl::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Refl',
        'pathMin'   => $root . '/src/MethodMin/Refl',
        'pathToClass' => $root . '/src/Refl.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\ID',
        'tool'   => $class = \Inilim\Tool\ID::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/ID',
        'pathMin'   => $root . '/src/MethodMin/ID',
        'pathToClass' => $root . '/src/ID.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Time',
        'tool'   => $class = \Inilim\Tool\Time::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Time',
        'pathMin'   => $root . '/src/MethodMin/Time',
        'pathToClass' => $root . '/src/Time.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Obj',
        'tool'   => $class = \Inilim\Tool\Obj::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Obj',
        'pathMin'   => $root . '/src/MethodMin/Obj',
        'pathToClass' => $root . '/src/Obj.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Assert',
        'tool'   => $class = \Inilim\Tool\Assert::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Assert',
        'pathMin'   => $root . '/src/MethodMin/Assert',
        'pathToClass' => $root . '/src/Assert.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Exp',
        'tool'   => $class = \Inilim\Tool\Exp::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Exp',
        'pathMin'   => $root . '/src/MethodMin/Exp',
        'pathToClass' => $root . '/src/Exp.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Enum',
        'tool'   => $class = \Inilim\Tool\Enum::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Enum',
        'pathMin'   => $root . '/src/MethodMin/Enum',
        'pathToClass' => $root . '/src/Enum.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\VD',
        'tool'   => $class = \Inilim\Tool\VD::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/VD',
        'pathMin'   => $root . '/src/MethodMin/VD',
        'pathToClass' => $root . '/src/VD.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\Check',
        'tool'   => $class = \Inilim\Tool\Check::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Check',
        'pathMin'   => $root . '/src/MethodMin/Check',
        'pathToClass' => $root . '/src/Check.php',
    ],
    [
        'method' => 'Inilim\Tool\Method\PF',
        'tool'   => $class = \Inilim\Tool\PF::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/PF',
        'pathMin'   => $root . '/src/MethodMin/PF',
        'pathToClass' => $root . '/src/PF.php',
    ],
];
