<?php

$root = \dirname(__DIR__);
return [
    [
        'method' => 'Inilim\Tool\Method\File',
        'tool'   => $class = \Inilim\Tool\File::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/File',
        'pathMin'   => $root . '/src/MethodMin/File',
    ],
    [
        'method' => 'Inilim\Tool\Method\Path',
        'tool'   => $class = \Inilim\Tool\Path::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Path',
        'pathMin'   => $root . '/src/MethodMin/Path',
    ],
    [
        'method' => 'Inilim\Tool\Method\Arr',
        'tool'   => $class = \Inilim\Tool\Arr::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Arr',
        'pathMin'   => $root . '/src/MethodMin/Arr',
    ],
    [
        'method' => 'Inilim\Tool\Method\Integer',
        'tool'   => $class = \Inilim\Tool\Integer::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Integer',
        'pathMin'   => $root . '/src/MethodMin/Integer',
    ],
    [
        'method' => 'Inilim\Tool\Method\Double',
        'tool'   => $class = \Inilim\Tool\Double::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Double',
        'pathMin'   => $root . '/src/MethodMin/Double',
    ],
    [
        'method' => 'Inilim\Tool\Method\Data',
        'tool'   => $class = \Inilim\Tool\Data::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Data',
        'pathMin'   => $root . '/src/MethodMin/Data',
    ],
    [
        'method' => 'Inilim\Tool\Method\String',
        'tool'   => $class = \Inilim\Tool\Str::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/String',
        'pathMin'   => $root . '/src/MethodMin/String',
    ],
    [
        'method' => 'Inilim\Tool\Method\Other',
        'tool'   => $class = \Inilim\Tool\Other::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Other',
        'pathMin'   => $root . '/src/MethodMin/Other',
    ],
    [
        'method' => 'Inilim\Tool\Method\Json',
        'tool'   => $class = \Inilim\Tool\Json::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Json',
        'pathMin'   => $root . '/src/MethodMin/Json',
    ],
    [
        'method' => 'Inilim\Tool\Method\FS',
        'tool'   => $class = \Inilim\Tool\FS::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/FS',
        'pathMin'   => $root . '/src/MethodMin/FS',
    ],
    [
        'method' => 'Inilim\Tool\Method\Zip',
        'tool'   => $class = \Inilim\Tool\Zip::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Zip',
        'pathMin'   => $root . '/src/MethodMin/Zip',
    ],
    [
        'method' => 'Inilim\Tool\Method\Refl',
        'tool'   => $class = \Inilim\Tool\Refl::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Refl',
        'pathMin'   => $root . '/src/MethodMin/Refl',
    ],
    [
        'method' => 'Inilim\Tool\Method\ID',
        'tool'   => $class = \Inilim\Tool\ID::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/ID',
        'pathMin'   => $root . '/src/MethodMin/ID',
    ],
    [
        'method' => 'Inilim\Tool\Method\Time',
        'tool'   => $class = \Inilim\Tool\Time::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Time',
        'pathMin'   => $root . '/src/MethodMin/Time',
    ],
    [
        'method' => 'Inilim\Tool\Method\Obj',
        'tool'   => $class = \Inilim\Tool\Obj::class,
        'nameClass'   => \basename($class),
        'path'   => $root . '/src/Method/Obj',
        'pathMin'   => $root . '/src/MethodMin/Obj',
    ],
];
