<?php

namespace Inilim\Tool\Method\Lar{function dataFill():\Closure{\Inilim\Tool\Method\Assert\__notArgsHere(__FUNCTION__,\func_num_args());return static function(&$target,$key,$value){return \Inilim\Tool\Method\Lar\dataSet()($target,$key,$value,false);};}if(!\Inilim\Tool\Lar::__definedIfNot('dataSet')){
    function dataSet():\Closure{\Inilim\Tool\Method\Assert\__notArgsHere(__FUNCTION__,\func_num_args());return static function(&$target,$key,$value,$overwrite=true){$segments=\is_array($key)?$key:\explode('.',$key);if(($segment=\array_shift($segments))==='*'){if(!\Inilim\Tool\Method\LarArr\accessible($target)){$target=[];}if($segments){foreach($target as&$inner){\Inilim\Tool\Method\Lar\dataSet()($inner,$segments,$value,$overwrite);}}elseif($overwrite){foreach($target as&$inner){$inner=$value;}}}elseif(\Inilim\Tool\Method\LarArr\accessible($target)){if($segments){if(!\Inilim\Tool\Method\LarArr\exists($target,$segment)){$target[$segment]=[];}\Inilim\Tool\Method\Lar\dataSet()($target[$segment],$segments,$value,$overwrite);}elseif($overwrite||!\Inilim\Tool\Method\LarArr\exists($target,$segment)){$target[$segment]=$value;}}elseif(\is_object($target)){if($segments){if(!isset($target ->{$segment})){$target ->{$segment}=[];}\Inilim\Tool\Method\Lar\dataSet()($target ->{$segment},$segments,$value,$overwrite);}elseif($overwrite||!isset($target ->{$segment})){$target ->{$segment}=$value;}}else{$target=[];if($segments){\Inilim\Tool\Method\Lar\dataSet()($target[$segment],$segments,$value,$overwrite);}elseif($overwrite){$target[$segment]=$value;}}return $target;};}
    }}namespace Inilim\Tool\Method\Assert{if(!\Inilim\Tool\Assert::__definedIfNot('__notArgsHere')){
    function __notArgsHere(string $fnName,int $countArgs){if($countArgs!==0){$fnName=\basename($fnName);throw new \InvalidArgumentException(\sprintf('%s()(...) OR %s()->__invoke(...) <-- The arguments were passed to the wrong place',$fnName,$fnName));}}
    }}namespace Inilim\Tool\Method\LarArr{if(!\Inilim\Tool\LarArr::__definedIfNot('accessible')){
    function accessible($value){return \is_array($value)||$value instanceof \ArrayAccess;}
    }if(!\Inilim\Tool\LarArr::__definedIfNot('exists')){
    function exists($array,$key){if($array instanceof \ArrayAccess){return $array -> offsetExists($key);}if(\is_float($key)||\is_null($key)){$key=(string) $key;}return \array_key_exists($key,$array);}
    }}