<?php

namespace Inilim\Tool\Method\Lar{function dataForget():\Closure{\Inilim\Tool\Method\Assert\__notArgsHere(__FUNCTION__,\func_num_args());return static function(&$target,$key){$segments=\is_array($key)?$key:\explode('.',$key);if(($segment=\array_shift($segments))==='*'&&\Inilim\Tool\Method\LarArr\accessible($target)){if($segments){foreach($target as&$inner){\Inilim\Tool\Method\Lar\dataForget()($inner,$segments);}}}elseif(\Inilim\Tool\Method\LarArr\accessible($target)){if($segments&&\Inilim\Tool\Method\LarArr\exists($target,$segment)){\Inilim\Tool\Method\Lar\dataForget()($target[$segment],$segments);}else{\Inilim\Tool\Method\LarArr\forget()($target,$segment);}}elseif(\is_object($target)){if($segments&&isset($target ->{$segment})){\Inilim\Tool\Method\Lar\dataForget()($target ->{$segment},$segments);}elseif(isset($target ->{$segment})){unset($target ->{$segment});}}return $target;};}}namespace Inilim\Tool\Method\Assert{if(!\Inilim\Tool\Assert::__definedIfNot('__notArgsHere')){
    function __notArgsHere(string $fnName,int $countArgs){if($countArgs!==0){$fnName=\basename($fnName);throw new \InvalidArgumentException(\sprintf('%s()(...) OR %s()->__invoke(...) <-- The arguments were passed to the wrong place',$fnName,$fnName));}}
    }}namespace Inilim\Tool\Method\LarArr{if(!\Inilim\Tool\LarArr::__definedIfNot('accessible')){
    function accessible($value){return \is_array($value)||$value instanceof \ArrayAccess;}
    }if(!\Inilim\Tool\LarArr::__definedIfNot('exists')){
    function exists($array,$key){if($array instanceof \ArrayAccess){return $array -> offsetExists($key);}if(\is_float($key)||\is_null($key)){$key=(string) $key;}return \array_key_exists($key,$array);}
    }if(!\Inilim\Tool\LarArr::__definedIfNot('forget')){
    function forget():\Closure{\Inilim\Tool\Method\Assert\__notArgsHere(__FUNCTION__,\func_num_args());return static function(&$array,$keys){$original=&$array;$keys=(array) $keys;if(\count($keys)===0){return;}foreach($keys as $key){if(\Inilim\Tool\Method\LarArr\exists($array,$key)){unset($array[$key]);continue;}$parts=\explode('.',$key);$array=&$original;while(\count($parts)>1){$part=\array_shift($parts);if(isset($array[$part])&&\Inilim\Tool\Method\LarArr\accessible($array[$part])){$array=&$array[$part];}else{continue 2;}}unset($array[\array_shift($parts)]);}};}
    }}